kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql
  namespace: expense
  labels:
    component: mysql
    tier: database
    project: expense

spec:
  replicas: 2
  selector:
    matchLabels:
      component: mysql
      tier: database
      project: expense

  template:
    metadata:

      labels:
        component: mysql
        tier: database
        project: expense
      
    spec:
      containers:
      - name: mysql
        image: pudviks/mysql:1.0



apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    component: mysql
    project: expense
    tier: database
    
  ports:
  - protocol: TCP
    port: 3306 #service-port
    targetPort: 3306 #target-port
    

    






